<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Core\Security;
use App\Entity\Dev;
use App\Entity\Entreprise;
use App\Entity\Utilisateur;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\UtilisateurRepository;
use App\Form\DevType;
use App\Form\LogInType;
use App\Form\EntType;

use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;

class SecurityController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/login', name: 'app_login')]
    public function login(Request $request, ManagerRegistry $doctrine): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('app_home_page');
        }

        $error = null;
        $lastUsername = '';

        if (/*$username != null && $password != null*/false) {
            // Récupérer les données du formulaire


            // Recherche de l'utilisateur par nom
            $user = $doctrine->getRepository(Utilisateur::class)->findOneBy(['nom' => $username]);

            if ($user && password_verify($password, $user->getPassword())) {
                // Connexion réussie, rediriger l'utilisateur
                return $this->redirectToRoute('app_home_page');
            } else {
                // Message d'erreur générique
                $error = 'Identifiants incorrects.';
            }
        }

        // Rendu du formulaire dans la vue
        return $this->render('security/index.html.twig', [
            'error' => $error,
            'last_username' => $lastUsername,
        ]);
    }

    #[Route('/logout', name: 'app_logout')]
    public function logout(): void
    {
        // Ce contrôleur ne sera jamais exécuté, Symfony gère la déconnexion automatiquement.
    }

    #[Route('/inscriptionD', name: 'app_registerD')]
    public function inscriptionD(Request $request): Response
    {
        $dev = new Dev();
        $form = $this->createForm(DevType::class, $dev);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $devData = $form->getData();
            $hash = password_hash($devData->getPassword(), PASSWORD_BCRYPT);
            $dev->setPassword($hash);

            $file = $form->get('avatar')->getData();
            $tabExt = array('jpg', 'png', 'jpeg');

            if (in_array(strtolower($file->guessExtension()), $tabExt)) // je vérifie que le fichier soit de la bonne extension
            {
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension(); // je génère un nom de fichier UNIQUE
                try {
                    $file->move($this->getParameter('app.photos_dossier'), $fileName); // je range le fichier uploadé au bon endroit
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $dev->setAvatar($fileName);

                $this->entityManager->persist($dev);
                $this->entityManager->flush();
                return $this->redirectToRoute('app_home_page');
            }
        }
        return $this->render('security/inscriptionD.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/inscriptionE', name: 'app_registerE')]
    public function inscriptionE(Request $request): Response
    {
        $ent = new Entreprise();
        $form = $this->createForm(EntType::class, $ent);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entData = $form->getData();
            $hash = password_hash($entData->getPassword(), PASSWORD_BCRYPT);
            $ent->setPassword($hash);

            $this->entityManager->persist($ent);
            $this->entityManager->flush();
            return $this->redirectToRoute('app_home_page');
        }

        return $this->render('security/inscriptionE.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
