server {
    listen 80;
    server_name localhost;

    root /var/www/public;  # Répertoire public de Symfony
    index index.php index.html;

    # Configuration pour Symfony (rediriger les requêtes vers index.php)
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Gestion des fichiers PHP avec PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;  # Nom du conteneur PHP-FPM défini dans docker-compose
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Refuser l'accès aux fichiers cachés (exemple : .env)
    location ~ /\. {
        deny all;
    }
}
